## JOINT EVENTS AND JOINT PROBABILITY
- Looking at components  or elements of one events that are also present in another event.

In [1]:
## two events
A = {2,3,4}
B = {3,4,6}
SS={1,2,3,4,5,6}

## use a loop

joint_event = [x for x in A if x in B]
joint_event

joint_prob = len(joint_event)/len(SS)
joint_prob

0.3333333333333333

## Using the housing dataset
a). Find the probability of getting a house with a basement as well as air conditioning.

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [5]:
data_sample_space= data.shape[0]

In [6]:

joint_events = data[(data["basement"]=='yes')&(data['airconditioning']=='yes')]
joint_events

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,3920000,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
356,3773000,2520,5,2,1,no,no,yes,no,yes,1,no,furnished
415,3395000,4785,3,1,2,yes,yes,yes,no,yes,1,no,furnished
431,3290000,3180,4,1,2,yes,no,yes,no,yes,0,no,unfurnished
461,3080000,4960,2,1,1,yes,no,yes,no,yes,0,no,unfurnished

In [7]:
no_joint_event = joint_events.shape[0]
no_joint_event

66

In [8]:
prob = no_joint_event/data_sample_space
print(f"{prob:.3}")

0.121

# Find the probability of getting a house that is on the main road and hass more than 2 stories.

In [9]:
data['stories']

0      3
1      4
2      2
3      2
4      2
      ..
540    1
541    1
542    1
543    1
544    2
Name: stories, Length: 545, dtype: int64

In [14]:
joint_events = data[(data["mainroad"]=="yes")&(data["stories"] > 2)]
no_joint_event = joint_event.shape[0]

total = data.shape[0]

prob = no_joint_event/total
print(f"{prob:.3}")

0.0239

# Find the probability of getting a house that is semi-furnished and has no guest room but has an AC.

In [ ]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [ ]:
data['guestroom']

0       no
1       no
2       no
3       no
4      yes
      ...
540     no
541     no
542     no
543     no
544     no
Name: guestroom, Length: 545, dtype: str

In [13]:
joint_event = data[(data["furnishingstatus"]=="semi-furnished")&(data["guestroom"]=="yes")&(data["airconditioning"]=="yes")]
joint_event

no_joint_event=joint_event.shape[0]

total = data.shape[0]

probability = no_joint_event/total
print(f"{probability:.3}")

0.0239